
import type { Metadata } from "next";
import { Navbar } from "@/components/navbar";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/providers/providers";
const rubik = Rubik({
  variable: "--font-rubik",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable}  antialiased`}>
      <Providers>
          <Navbar />
          {children}
        </Providers>
        ;
      </body>
    </html>
  );
}
